### ISSUE TITLE
backend: add alerting (to Slack) if critical issues are detected

### ISSUE THREAD

**Issue by pawlh** [softwareconstruction240/autograder#100]
- continual crashes
- frozen queue
- many consecutive failed `mvn package` attempts
- etc.

**Comment by DallinFromEarth** [comment]
Maybe look into https://uptime.bot/

**Comment by frozenfrank** [comment]
@19mdavenport I know we implemented some kind of uptime monitoring system when we had the huge spout of issues last semester. Does that address this issue, or is there more work to do?

**Comment by 19mdavenport** [comment]
@frozenfrank I'm not sure what you mean by that. Are you talking about the AWS feature Professor Jensen included that restarted it if it went unresponsive?

**Comment by frozenfrank** [comment]
@19mdavenport Yes, that's exactly what I'm referring to. Does that resolve this issue?

**Comment by 19mdavenport** [comment]
I'm not sure we need this anymore. Since Professor Jensen upgraded the instance to medium, I'm not aware of any problems that have happened. Plus, it would be a pain to reconfigure the bot every new semester.

@frozenfrank Maybe, but not a log we can see. However, the autograder server would log that it restarted
