### ISSUE TITLE
frontend: fix frontend AM/PM display

### ISSUE THREAD

**Issue by pawlh** [softwareconstruction240/autograder#112]
A submission made at 12:24 PM is incorrectly showing as 12:24 AM

![Image](https://github.com/softwareconstruction240/autograder/assets/10139415/05378a4d-2df3-4aa7-85d3-1d112712065a)

**Comment by frozenfrank** [comment]
This is currently being addressed by using a native date formatting method. If we want a more flexible option that allows us to format the dates in more custom ways, I recommend [MomentJS](https://momentjs.com/).

**Comment by frozenfrank** [comment]
Note that this bug is currently also present in all timestamps across the app, including in the submissions list. Here is a screenshot of the issue in another place:

<img width="750" alt="image" src="https://github.com/softwareconstruction240/autograder/assets/19808440/fc8b763c-c137-463b-83dd-e279a8ef8527">
