### ISSUE TITLE
backend: add ability to clear testStudent from the database for testing

### ISSUE THREAD

**Issue by DallinFromEarth** [softwareconstruction240/autograder#122]

**Comment by frozenfrank** [comment]
@DallinFromEarth Can you add some additional description to this issue? Which fields need to be cleared from the database in order for this to be complete?

**Comment by pawlh** [comment]
@DallinFromEarth to add to @frozenfrank's comment...

What additional functionality would you like to see? Currently test student's submission history is cleared whenever `Test Student Mode` is entered and a fresh `repo_url` is pulled from Canvas

**Comment by frozenfrank** [comment]
When @pawlh and I were working on a different issue, I remember this issue coming up frequently. We needed to keep rerunning the sat student's code, but it wouldn't let us do it because the test student had a submission for the phase already.

The workaround is to enter test student mode, and then get back to admin mode which clears out the value. However, that was a pain in the butt. A button in the admin dashboard the clears the submission from test student would be very helpful.

**Comment by DallinFromEarth** [comment]
The idea was just to make testing easier so you didn't have to go change the GitHub for the test student every time you tried testing something. But if all you need to do is log out, then that's good enough for me

**Comment by pawlh** [comment]
> A button in the admin dashboard the clears the submission from test student would be very helpful.
Hmm, yeah I see how that could be useful. I'd say that after adding this the **Test Student Mode** button belongs in its own tab, just because it is getting a little big to be a constant banner for admins

**Comment by DallinFromEarth** [comment]
This is being made irrelevant by #240. Additionally, the test student is already cleared each time you log into it
