### ISSUE TITLE
hold off submitting scores for low commit submissions

### ISSUE THREAD

**Issue by pawlh** [softwareconstruction240/autograder#160]
Requirements per the professors:
- Minimum requirement is 10 commits on at least 3 different days
- The autograder will enforce this and fail the submission with a message that they have to pass off in person
- The TA doing the in person grading can, at their discretion, deduct 10% if it looks like they are not learning the value/habit of repeated commits

**Comment by pawlh** [comment]
A possible implementation:

A column is added to the existing `submission` table: `approved`
   - Submissions with sufficient commits will automatically be approved and submitted to Canvas
   - Submissions lacking commits will have this field set to false. Unapproved submissions will be displayed on the admin section of the frontend, where TAs will be able to approve with full points or approve with a deduction

**Comment by pawlh** [comment]
We should consider this blocked by #76 as that issue will significantly change the backend grading structure

**Comment by frozenfrank** [comment]
@DallinFromEarth and @pawlh reached this conclusion:
> We can write it so it only starts blocking them after they’ve passed all the tests, so if they pass all the pass off tests, AND on that submission they don’t have enough commits, THEN we block them

Based on that resolution, there may be a reason to make this phase blocking take effect sooner, but the exact line hasn't been defined. We'll build the line as described above for now, and listen to updates from the professors.

@leesjensen @jerodw @rodham FYI If you want to weight in on this issue

**Comment by frozenfrank** [comment]
We need to figure out what counts as the anchor for development from this phase. The code is currently referencing the first passing submission for the current phase, but we really want to be comparing commits from the last passing submission of the previous phase to the first passing submission of the current phase. 

Then we start running into issues with edge cases where students may author all their commits with space in between them, but then, the autograder will judge them based on the commits authored between the timestamps of the submissions to students which could lead to frustrations. 

Ideally, we would compare the commits only since the HEAD HASH of the most recent passing submission for the previous phase. In this scenario, we would only count a commit for this purpose if it is _not an ancestor_ of the HEAD HASH (they could have merged in commits, etc...).
