### ISSUE TITLE
backend: Clean up requests for DB credentials

### ISSUE THREAD

**Issue by frozenfrank** [softwareconstruction240/autograder#166]
Take ear to the following observations:
* In the setup instructions, there is a reference to a `src/main/resources/db.properties` file 
* That file does not exist in the current repository
* The "Environment Variables" portion of root README.md file shows environment variables that define the DB username, password, url, and name
* There are two other files that contains this information:
    * `phases/phase4/resources/db.properties`
    * `phases/phase6/resources/db.properties`
* Those other files seem to be stale references to old settings

Based on the information currently available, I propose that we remove these outdated files and rely wholly on the environment variables. The README.md file should be updated to reflect these changes.

Note that there may be legitimate concern for database access with later phases. I'm not informed enough about how those files are supposed to access student's databases. Please comment with any relevant information.

**Comment by pawlh** [comment]
Yes to half of this.

The reference in `README.md` to `src/main/resources/db.properties` is outdated and should be removed.

As for the `db.properties` files in the `phases/` path, those are different and mostly not related to the autograder itself. We will need those in order to run students' code. We might not end up just copying them in, but the specific procedure has not yet been worked out. (see the instructions for Phase 4, step 1: https://github.com/softwareconstruction240/softwareconstruction/blob/main/chess/4-database/database.md)

**Comment by frozenfrank** [comment]
@pawlh Thanks for the information! I'll save the notes about the `db.properties` for later, but I have addressed this concern:

> The reference in README.md to src/main/resources/db.properties is outdated and should be removed.
This is handled in #167.

**Comment by pawlh** [comment]
I've lost track of which PR it was, but I believe this has been addressed by @19mdavenport's db changes that dynamically generate student db info for each grading session
