### ISSUE TITLE
admin: add option to pause new submissions

### ISSUE THREAD

**Issue by pawlh** [softwareconstruction240/autograder#87]
Before doing any maintenance, we should be able to pause new submissions so that any reboot does not interrupt projects in the grading queue

**Comment by DallinFromEarth** [comment]
Will be solved with #324

**Comment by frozenfrank** [comment]
@DallinFromEarth Since this isn't _yet_ closed, I'm going to reopen it. However, I've marked it as as tracking the `324-program-config` branch so that when the `324-...` branch is merged, this issue will close automatically. 

This is more easily tracked with a PR where the PR can explicitly close multiple issues. However, this approach also works.
